#!/bin/sh
# This script establishes a loop that prints every odd-numbered argument

echo $0				# Print name of running command (ie. script file name)

while [ $# -gt 0 ]			# Check if there are arguments listed
do
	echo $1			# If so, print first argument, then
if [ $# -gt 1 ]			# Check how many arguments are left
then	
	shift			# If 2 or more, discard first two arguments, then shift each argument over
	shift			# This ensures only odd arguments are considered

else				# If only 1 argument is left, discard argument
	shift			# Shift once
fi
done
exit				# Exit script
